config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

class LandingConstraint
  def self.matches?(request)
    domains = %w{ www.lvh.me lvh.me localhost www.localhost }
    case request.subdomain
    when '', 'www'
     domains.include?(request.domain)
    else
      false
    end
  end
end

Rails.application.routes.draw do

  resources :community_product_properties
  resources :community_products

  root to: "home#index"
  get '/product/show', to: "home#show"
  resources :shop_registration

  resources :main_products
  # devise_for :site_admins
  devise_for :site_admins, controllers: {
    sessions: 'site_admins/sessions'
  }
  as :site_admin do
    get '/site_admin_login', to: 'site_admins/sessions#new', as: 'site_admin_login'
    get '/site_admin_logout', to: 'site_admins/sessions#destroy', as: 'site_admin_logout', via: Devise.mappings[:site_admin].sign_out_via
    get '/site_admin_signup', to: 'site_admins/registrations#new', as: 'site_admin_signup'
  end


  devise_for :customers, controllers: {
    sessions: 'customers/sessions'
  }
  as :customer do
    get '/customer_login', to: 'customers/sessions#new', as: 'customer_login'
    get '/customer_logout', to: 'customers/sessions#destroy', as: 'customer_logout', via: Devise.mappings[:customer].sign_out_via
    get '/customer_signup', to: 'customers/registrations#new', as: 'customer_signup'
  end

  # For the ShopknektV2
  constraints LandingConstraint do
    resources :themes
    namespace :control_panel do
      resources :shops

    end
  end

  # For Tenants sites.
  constraints SubdomainConstraint do
    namespace :control_panel do
      resources :product_segments
      resources :categories
      resources :subcategories
      resources :products
      resources :product_properties

      resources :community_products
    end
    # devise_for :customers
    # devise_for :customers, controllers: {
    #   sessions: 'customers/sessions'
    # }
    resources :orders
    resources :order_items
    resources :carts
      resources :shipping_addresses

    resource :cart, only: %i[update show destroy] do
      member do
        put :remove_item
        get :checkout_address
        get :checkout_review
        get :checkout_payment
      end
    end

    resources :customers, only: %i[new create update] do
      # devise_for :users, only: [ :new, :create, :update ]
      # as :user do
      resources :orders
    end

  end

end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :theme
  belongs_to :main_product

  after_create :create_tenant

  has_many :shop_site_admins
  has_many :site_admin, through: :shop_site_admins

  has_many :shop_community_products
  has_many :community_products, through: :shop_community_products

  before_save do
    self.subdomain = self.shop_name.parameterize if self.shop_name_changed?
  end

  def create_tenant
    Apartment::Tenant.create(subdomain)
  end
end

app/controllers/control_panel/shops_controller.rb
class ControlPanel::ShopsController < ApplicationController
  before_action :authenticate_site_admin!
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = current_site_admin.shop
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        current_site_admin.shop_site_admins.create!(shop: @shop)
        format.html { redirect_to control_panel_shops_path, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to control_panel_shop_path(@shop), notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to control_panel_shops_path, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:shop_name, :subdomain, :domain, :theme_id, :main_product_id)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    byebug
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        current_site_admin.shop_site_admin.create!(shop: @shop)
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:shop_name, :subdomain, :domain, :theme_id, :main_product_id)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :shop_name %>
    <%= form.text_field :shop_name, id: :shop_shop_name %>
  </div>

  <div class="field">
    <%= form.label :subdomain %>
    <%= form.text_field :subdomain, id: :shop_subdomain %>
  </div>

  <div class="field">
    <%= form.label :domain %>
    <%= form.text_field :domain, id: :shop_domain %>
  </div>

  <div class="field">
    <%= form.label :theme_id %>
    <%= form.text_field :theme_id, id: :shop_theme_id %>
  </div>

  <div class="field">
    <%= form.label :main_product_id %>
    <%= form.text_field :main_product_id, id: :shop_main_product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>Shop name</th>
      <th>Subdomain</th>
      <th>Domain</th>
      <th>Theme</th>
      <th>Main product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.shop_name %></td>
        <td><%= shop.subdomain %></td>
        <td><%= shop.domain %></td>
        <td><%= shop.theme %></td>
        <td><%= shop.main_product %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shop name:</strong>
  <%= @shop.shop_name %>
</p>

<p>
  <strong>Subdomain:</strong>
  <%= @shop.subdomain %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @shop.domain %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @shop.theme %>
</p>

<p>
  <strong>Main product:</strong>
  <%= @shop.main_product %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>