config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

class LandingConstraint
  def self.matches?(request)
    domains = %w{ www.lvh.me lvh.me localhost www.localhost }
    case request.subdomain
    when '', 'www'
     domains.include?(request.domain)
    else
      false
    end
  end
end

Rails.application.routes.draw do

  resources :community_product_properties
  resources :community_products

  root to: "home#index"
  get '/product/show', to: "home#show"
  resources :shop_registration

  resources :main_products
  # devise_for :site_admins
  devise_for :site_admins, controllers: {
    sessions: 'site_admins/sessions'
  }
  as :site_admin do
    get '/site_admin_login', to: 'site_admins/sessions#new', as: 'site_admin_login'
    get '/site_admin_logout', to: 'site_admins/sessions#destroy', as: 'site_admin_logout', via: Devise.mappings[:site_admin].sign_out_via
    get '/site_admin_signup', to: 'site_admins/registrations#new', as: 'site_admin_signup'
  end


  devise_for :customers, controllers: {
    sessions: 'customers/sessions'
  }
  as :customer do
    get '/customer_login', to: 'customers/sessions#new', as: 'customer_login'
    get '/customer_logout', to: 'customers/sessions#destroy', as: 'customer_logout', via: Devise.mappings[:customer].sign_out_via
    get '/customer_signup', to: 'customers/registrations#new', as: 'customer_signup'
  end

  # For the ShopknektV2
  constraints LandingConstraint do
    resources :themes
    namespace :control_panel do
      resources :shops

    end
  end

  # For Tenants sites.
  constraints SubdomainConstraint do
    namespace :control_panel do
      resources :product_segments
      resources :categories
      resources :subcategories
      resources :products
      resources :product_properties

      resources :community_products
    end
    # devise_for :customers
    # devise_for :customers, controllers: {
    #   sessions: 'customers/sessions'
    # }
    resources :orders
    resources :order_items
    resources :carts
      resources :shipping_addresses

    resource :cart, only: %i[update show destroy] do
      member do
        put :remove_item
        get :checkout_address
        get :checkout_review
        get :checkout_payment
      end
    end

    resources :customers, only: %i[new create update] do
      # devise_for :users, only: [ :new, :create, :update ]
      # as :user do
      resources :orders
    end

  end

end

app/models/cart.rb
class Cart 
  attr_reader :session

  def initialize(session)
    #byebug
    @session = session
  end

  def items
    #session.map do |id, quantity, size, color|
    session.map do |id, quantity, size, color|
      #byebug
      CartItem.new(Product.find(id), quantity[0], quantity[1], quantity[2])
    end
  end

  def total
    items.map { |item| item.total }.inject(&:+)
  end

  def remove_item(remove_item_param)
    if id = remove_item_param[:product_id]
      session.delete(id)
    end
    session
  end

  def update(carts_param)
    #byebug
    if id = carts_param[:product_id]
      quantity = carts_param[:quantity]
      size = carts_param[:size]
      color = carts_param[:color]
      if session[id].nil?
        tquantity = quantity || (session[id].to_i + 1).to_s
      else
        tquantity = quantity || (session[id][0].to_i + 1).to_s
      end
      session[id] = tquantity, size, color
    end
    session
  end

  def destroy
    session = {}
  end

  def count
    session.present? ? "(#{calculate_count})" : nil
  end

  def empty?
    items.empty?
  end

private
  def calculate_count
    #session.values.map(&:to_i).reduce(&:+)
    if session.values.length > 1
      session.map { |x, y| y[0].to_i }.reduce :+
    else
      session.values[0][0].to_i
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    before_action :find_or_create_cart

    def show
      @product = Product.find(params[:id])
    end


    def update
      this_shop_product = params[:carts][:product_id].to_i
      temp_product = Product.find_by(id: this_shop_product)

      # if temp_product.source == "community"
      #   @this_product = Product.find_by(id: temp_product.source_product_id)
      # else
        @this_product = Product.find_by(id: temp_product.id)
      # end
      #
      if params[:carts][:quantity].present?
        this_quantity = params[:carts][:quantity].to_i
      else
        this_quantity = 1
      end
      #
      if @this_product.quantity.to_i < this_quantity
      #   # byebug
        redirect_to :back, :notice  => "Unfountately we have #{temp_product.quantity} stock available. Please enter quanity equal to or less than this."
      else
        if @this_product.product_properties.pluck(:size).uniq != [""]
          size_required = true
        end
        if @this_product.product_properties.pluck(:color).uniq != [""]
          color_required = true
        end
        notice = ""
      #   #byebug
        if size_required == true
          if params[:carts][:size].nil? || params[:carts][:size] == ""
            size_required_error = true
          end
        end
      #
        if color_required == true
          if params[:carts][:color].nil? || params[:carts][:color] == ""
            color_required_error = true
          end
        end
      #
        if size_required_error == true
          notice = "Size is required to place the order."
        elsif color_required_error == true
          if notice.empty?
            notice = "Color is required to place the order."
          else
            notice = "Size & Color information required to place the order."
          end
        end
      #
        if size_required_error == true || color_required_error == true
          redirect_to :back, :notice => notice
        else
          session[:cart] = current_cart.update(params[:carts])
          if buy_now?
            redirect_to cart_path
          else
            redirect_to product_show_path(params[:carts][:product_id].to_i)
          end
        end
      end
    end

    def checkout_review
      # @billing_address = BillingAddress.find_by(user_id: current_customer.id, primary: true)
      @shipping_address = ShippingAddress.find_by(customer_id: current_customer.id)
      session[:return_to] = request.fullpath
    end

    def checkout_payment
      # @billing_address = BillingAddress.find_by(user_id: current_customer.id, primary: true)
      @shipping_address = ShippingAddress.find_by(customer_id: current_customer.id)
      session[:return_to] = request.fullpath
    end

    def checkout_address
      # byebug
      if current_customer
        @shipping_addresses = ShippingAddress.where(customer_id: current_customer.id)
        @shipping_address = ShippingAddress.new
        session[:return_to] = request.fullpath
      else
        redirect_to new_customer_registration_path
      end
    end


    def remove_item
      session[:cart] = current_cart.remove_item(params[:remove_item])
      redirect_to(:back)
    end

    def destroy
      session[:cart] = current_cart.destroy
      redirect_to root_path, :notice  => "Cart cleared."
    end

    private

      def buy_now?
        params[:commit] == "Buy Now"
      end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_item.html.erb
<% current_cart.items.each do |cart_item| %>
  <tr id="product_<%= cart_item.product.id %>" class="hidden-xs">
    <td style="max-width: 75px">
      <%#= image_tag product_small_image_path(cart_item.product), class: "img-responsive" %>
    </td>
    <td><%= link_to cart_item.title, product_show_path(cart_item.product) %></td>
    <% if cart_item.color.nil? %>
      <td>-</td>
    <% else %>
      <td><%= cart_item.color %></td>
    <% end %>
    <% if cart_item.size.nil? %>
      <td>-</td>
    <% else %>
      <td><%= cart_item.size %></td>
    <% end %>
    <%= simple_form_for :carts, url: '/cart', method: :put do |f| %>
      <td class="text-right">
        <%= f.hidden_field :product_id, value: cart_item.product.id %>
        <%= f.input_field :quantity, value: cart_item.quantity, class: 'form-control' %>
        <%= f.hidden_field :color, value: cart_item.color %>
        <%= f.hidden_field :size, value: cart_item.size %>
        <%= button_tag(type: 'submit', class: "btn btn-primary") do %><%#= fa_icon "refresh" %> Update<% end %>
        </td>
      <% end %>
      <td><%= number_to_currency(cart_item.unit_price, unit: "₹ ") %></td>
      <td><%#= cart_item.percent_off %> %</td>
      <td colspan="2"><%= number_to_currency(cart_item.selling_price, unit: "₹ ") %></td>
      <td><%= link_to remove_item_cart_path(remove_item: { product_id: cart_item.product.id }), confirm: t('confirm'), method: :put do %><%#= fa_icon "trash-o" %><% end %>
      </td>
    </tr>
  <% end %>

app/views/carts/_cart_item_static.html.erb
<% current_cart.items.each do |cart_item| %>
  <tr id="product_<%= cart_item.product.id %>">
    <td style="max-width: 75px">
      <%#= image_tag product_small_image_path(cart_item.product), class: "img-responsive" %>
    </td>
    <td><%= link_to cart_item.title, product_show_path(cart_item.product) %></td>
    <% if cart_item.color.nil? %>
      <td>-</td>
    <% else %>
      <td><%= cart_item.color %></td>
    <% end %>
    <% if cart_item.size.nil? %>
      <td>-</td>
    <% else %>
      <td><%= cart_item.size %></td>
    <% end %>
    <td class="text-right">
      <%= cart_item.quantity %>
    </td>
    <td><%= number_to_currency(cart_item.unit_price, unit: "₹ ") %></td>
    <td><%#= cart_item.percent_off %> %</td>
    <td colspan="2"><%= cart_item.selling_price %></td>
  </tr>
<% end %>

app/views/carts/_checkout_button.html.erb
<% if current_customer %>
  <%= form_tag customer_orders_path(current_customer) do %>
    <% @order_reference = Razorpay::Order.create amount: (price * 100).to_i, currency: 'INR', receipt: 'TEST' %>

    <script
    src="https://checkout.razorpay.com/v1/checkout.js"
            data-key="<%= ENV['MERCHANT_KEY_ID'] %>"
            data-amount="<%= price * 100 %>"
            data-name="<%= @shop.shop_name %>"
            data-description="<%= description %>"
            data-image="/images/product.jpg"
            data-prefill.name="<%= "#{current_customer.full_name}" %>"
            data-prefill.email="<%= "#{current_customer.email}" %>"
            data-order_id="<%= "#{@order_reference.id}" %>"
            data-theme.color="#5091da">
    </script>
  <% end %>
<% else %>
  <%= button_to t('checkout'), customer_account_path_helper, class: 'btn btn-default', method: :get %>
<% end %>

app/views/carts/checkout_address.html.erb
<div id="all">
  <div id="content">
    <div class="container">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>Shopping cart</li>
        </ul>
        <div class="box text-center">
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
              <h1>Shopping cart</h1>
              <% if current_cart.empty? %>
                <p class="text-muted">
                  <%= t('cart.isempty') %>
                </p>
                <%= link_to t('back.home'), root_path, class: "btn btn-default" %>
              <% else %>
                <p class="text-muted">You currently have
                  <%= current_cart.items.count %> item(s) in your cart.</p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-9 clearfix" id="checkout">
        <div class="box">
          <ul class="nav nav-pills nav-justified">
            <li class="active">
              <a href="#">
                <i class="fa fa-map-marker"></i>
                <br>
                 Address
              </a>
            </li>
            <li class="disabled">
              <a href="#">
                <i class="fa fa-eye"></i>
                <br>
                 Order Review</a>
            </li>
            <li class="disabled">
              <a href="#">
                <i class="fa fa-money"></i>
                <br>
                 Payment Method</a>
            </li>
          </ul>
          <div class="content">
            <div class="row">
              <div class="col-md-12">
                <h3>Shipping Addresses</h3>
                <%# unless @shipping_addresses.nil? %>
                  <% @shipping_addresses.each do |shipping_address| %>
                    <div class="col-md-4 thumbnail" style="text-align: left;text-transform: capitalize;">
                      <p>
                        <%= shipping_address.line1 %>
                      </p>
                      <p>
                        <%= shipping_address.line2 %>
                      </p>
                      <p>
                        <%= shipping_address.zipcode %>
                      </p>
                      <p>
                        <%= shipping_address.city %>
                      </p>
                      <p>
                        <%= shipping_address.state %>
                      </p>
                      <p>
                        <%= shipping_address.country %>
                      </p>
                      <%# if shipping_address.primary %>
                        <!-- <span class="label label-primary">Primary</span> -->
                        <%# @primarycheck_shipping = true %>
                      <%# end %>
                      <hr/>
                      <p>
                        <%= link_to shipping_address, class: "btn btn-default" do %>
                          <%#= fa_icon "search" %>
                        <% end %>
                        <%= link_to edit_shipping_address_path(shipping_address), class: "btn btn-default"  do %>
                          <%#= fa_icon "pencil" %>
                        <% end %>
                        <%= link_to shipping_address, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }  do %>
                          <%#= fa_icon "trash" %>
                        <% end %>
                      </p>
                    </div>
                  <% end %>
                <%# end %>
              </div>
              <% if @shipping_addresses.count < 1 %>
                <%= render 'shipping_addresses/form' %>
                <%#= URI(request.referer).path %>
                <%#= link_to 'New shipping address', new_shipping_address_path, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
          <div class="box-footer">
            <div class="pull-left">
              <%#= link_to cart_path, class: 'btn btn-default' do %>
                Back to Cart
              <%# end %>
            </div>
            <div class="pull-right">
              <%# if @billing_address.nil? or @shipping_address.nil? %>
              <% if @shipping_address.nil? %>
                <%= link_to "#", class: 'btn btn-default disabled' do %>
                  Address required to Proceed
                  <%#= fa_icon "chevron-right" %>
                <% end %>
              <% else %>
                <%= link_to checkout_review_cart_path, class: 'btn btn-default' do %>
                  Proceed to Order Review
                  <%#= fa_icon "chevron-right" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box" id="order-summary">
          <div class="box-header">
            <h3>Order summary</h3>
          </div>
          <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <tr>
                  <td>Order subtotal</td>
                  <th>
                    <%= number_to_currency(current_cart.total, unit: "₹ ") %>
                  </th>
                </tr>
                <tr>
                  <td>Shipping and handling</td>
                  <th>0.00</th>
                </tr>
                <tr>
                  <td>Tax</td>
                  <th>0.00</th>
                </tr>
                <tr class="total">
                  <td>Total</td>
                  <th>
                    <%= number_to_currency(current_cart.total, unit: "₹ ") %>
                  </th>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <!-- /.col-md-3 -->
    </div>
    <!-- /.container -->
  </div>
  <!-- /#content -->
</div>

app/views/carts/checkout_payment.html.erb
<div id="all">
  <div id="content">
    <div class="container">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>Shopping cart</li>
        </ul>
        <div class="box text-center">
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
              <h1>Shopping cart</h1>
              <% if current_cart.empty? %>
                <p class="text-muted">
                  <%= t('cart.isempty') %>
                </p>
                <%= link_to t('back.home'), root_path, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-9 clearfix">
        <div class="box">
          <div class="row">
            <div class="col-md-12">
              <p>Name:
                <%= current_customer.full_name %>
              </p>
              <p>Email:
                <%= current_customer.email %>
              </p>
              <hr/>
            </div>
            <div class="col-md-6">
              <strong>Billing Address:</strong>
              <p>
                <%= @billing_address.line1 %>
              </p>
              <p>
                <%= @billing_address.line2 %>
              </p>
              <p>
                <%= @billing_address.zipcode %>
              </p>
              <p>
                <%= @billing_address.city %>
              </p>
              <p>
                <%= @billing_address.state %>
              </p>
              <p>
                <%= @billing_address.country %>
              </p>
            </div>
            <div class="col-md-6">
              <strong>Shipping Address:</strong>
              <p>
                <%= @shipping_address.line1 %>
              </p>
              <p>
                <%= @shipping_address.line2 %>
              </p>
              <p>
                <%= @shipping_address.zipcode %>
              </p>
              <p>
                <%= @shipping_address.city %>
              </p>
              <p>
                <%= @shipping_address.state %>
              </p>
              <p>
                <%= @shipping_address.country %>
              </p>
            </div>
            <div class="col-md-12">
              <hr/>
              <h4>Order of
                <%= number_to_currency(current_cart.total, unit: "₹ ") %> for
                <%= current_cart.items.map(&:title).join(",") %>.</h4>
              <p>Items will be dispatched within 24 to 48 hrs. We would keep you posted with delivery mode and airwayable number.</p>
            </div>
          </div>
          <div class="box-footer">
            <div class="pull-left">
              <%= link_to cart_path, class: 'btn btn-default' do %>
                Back to Cart
              <% end %>
            </div>
            <div class="pull-right">
              <%= render partial: 'checkout_button', locals: { price: current_cart.total, description: current_cart.items.collect(&:title).join(", ") } %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box" id="order-summary">
          <div class="box-header">
            <h3>Order summary</h3>
          </div>
          <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <tr>
                  <td>Order subtotal</td>
                  <th>
                    <%= number_to_currency(current_cart.total, unit: "₹ ") %>
                  </th>
                </tr>
                <tr>
                  <td>Shipping and handling</td>
                  <th>0.00</th>
                </tr>
                <tr>
                  <td>Tax</td>
                  <th>0.00</th>
                </tr>
                <tr class="total">
                  <td>Total</td>
                  <th>
                    <%= number_to_currency(current_cart.total) %>
                  </th>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <!-- /.col-md-3 -->
    </div>
    <!-- /.container -->
  </div>
  <!-- /#content -->
</div>

app/views/carts/checkout_review.html.erb
<div id="all">
  <div id="content">
    <div class="container">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>Shopping cart</li>
        </ul>
        <div class="box text-center">
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
              <h1>Order Review</h1>
              <% if current_cart.empty? %>
                <p class="text-muted">
                  <%= t('cart.isempty') %>
                </p>
                <%= link_to t('back.home'), root_path, class: "btn btn-default" %>
              <% else %>
                <p class="text-muted">You currently have
                  <%= current_cart.items.count %> item(s) in your cart.</p>
              <% end %>
            </div>
          </div>
        </div>
      </div>


      <div class="col-md-9 clearfix">
        <div class="box">
          <div class="row">
            <div class="col-md-12">
              <p>Name:
                <%= current_customer.full_name %>
              </p>
              <p>Email:
                <%= current_customer.email %>
              </p>
              <hr/>
            </div>
            <div class="col-md-6">
              <strong>Shipping Address:</strong>
              <p>
                <%= @shipping_address.line1 %>
              </p>
              <p>
                <%= @shipping_address.line2 %>
              </p>
              <p>
                <%= @shipping_address.zipcode %>
              </p>
              <p>
                <%= @shipping_address.city %>
              </p>
              <p>
                <%= @shipping_address.state %>
              </p>
              <p>
                <%= @shipping_address.country %>
              </p>
            </div>
          </div>
        </div>
        <div class="box">
          <div class="table-responsive hidden-xs">
            <table class="table">
              <thead>
                <tr>
                  <th colspan="2">
                    <%= t('product.self') %>
                  </th>
                  <th>Color</th>
                  <th>Size</th>
                  <th>
                    <%= t('product.quantity') %>
                  </th>
                  <th>
                    <%= t('product.originalprice') %>
                  </th>
                  <th>
                    <%= t('product.discount') %>
                  </th>
                  <th colspan="2">
                    <%= t('product.price') %>
                  </th>
                </tr>
              </thead>
              <tbody>
                <%= render partial: 'cart_item_static' %>
              </tbody>
              <tfoot>
                <tr>
                  <th colspan="5">Total</th>
                  <th colspan="2">
                    <%= number_to_currency(current_cart.total, unit: "₹ ") %>
                  </th>
                </tr>
              </tfoot>
            </table>
          </div>

          <div class="visible-xs">
            <%#= render partial: 'cart_item_static_mobile' %>
          </div>

          <div class="box-footer">
            <div class="pull-left">
              <%#= link_to cart_path, class: 'btn btn-default' do %>
                Back to Cart
              <%# end %>
            </div>
            <div class="pull-right">
              <%= render partial: 'checkout_button', locals: { price: current_cart.total, description: current_cart.items.collect(&:title).join(", ") } %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box" id="order-summary">
          <div class="box-header">
            <h3>Order summary</h3>
          </div>
          <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <tr>
                  <td>Order subtotal</td>
                  <th>
                    <%= number_to_currency(current_cart.total, unit: "₹ ") %>
                  </th>
                </tr>
                <tr>
                  <td>Shipping and handling</td>
                  <th>0.00</th>
                </tr>
                <tr>
                  <td>Tax</td>
                  <th>0.00</th>
                </tr>
                <tr class="total">
                  <td>Total</td>
                  <th>
                    <%= number_to_currency(current_cart.total, unit: "₹ ") %>
                  </th>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <!-- /.col-md-3 -->
    </div>
    <!-- /.container -->
  </div>
  <!-- /#content -->
</div>

app/views/carts/show.html.erb
<div id="all">
  <div id="content">
    <div class="container">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>Shopping cart</li>
        </ul>
        <div class="box text-center">
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
              <h1>Shopping cart</h1>
              <% if current_cart.empty? %>
                <p class="text-muted">
                  <%= t('cart.isempty') %>
                </p>
                <%= link_to t('back.home'), root_path, class: "btn btn-default" %>
              <% else %>
                <p class="text-muted">You currently have
                  <%= current_cart.items.count %> item(s) in your cart.</p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-9 clearfix">
        <div class="box">
          <div class="table-responsive hidden-xs">
            <table class="table">
              <thead>
                <tr>
                  <th colspan="2">
                    <%= t('product.self') %>
                  </th>
                  <th>Color</th>
                  <th>Size</th>
                  <th>
                    <%= t('product.quantity') %>
                  </th>
                  <th>
                    <%= t('product.originalprice') %>
                  </th>
                  <th>
                    <%= t('product.discount') %>
                  </th>
                  <th colspan="2">
                    <%= t('product.price') %>
                  </th>
                </tr>
              </thead>
              <tbody>
                <%= render partial: 'cart_item' %>
              </tbody>
              <tfoot>
                <tr>
                  <th colspan="5">Total</th>
                  <th colspan="2">
                    <%= number_to_currency(current_cart.total, unit: "₹ ") %>
                  </th>
                </tr>
              </tfoot>
            </table>
          </div>
          <div class="visible-xs">
            <%#= render partial: 'cart_item_mobile' %>
          </div>
          <!-- /.table-responsive -->
          <div class="box-footer">
            <div class="pull-left">
              <%= link_to root_path, class: "btn btn-default" do %>
                <%#= fa_icon "chevron-left" %> Continue shopping
              <% end %>
            </div>
            <div class="pull-right">
              <%= link_to cart_path, class: 'btn btn-default', method: :delete do %>
                <%#= fa_icon "trash-o" %>
                <%= t('cart.empty') %>
              <% end %>
              <%= link_to checkout_address_cart_path, class: 'btn btn-default' do %>
                Proceed to Checkout
                <%#= fa_icon "chevron-right" %>
              <% end %>
            </div>
          </div>


        </div>
        <!-- /.box -->
        <div class="row">
          <div class="row">
            <div class="col-md-12 col-sm-6">
              <div class="box">
                <h3>You may also like these products</h3>
              </div>
            </div>
            <%#= render @products.limit(6), class_name: "col-md-4 col-sm-6"  %>
          </div>
        </div>
      </div>
      <!-- /.col-md-9 -->
      <div class="col-md-3">
        <div class="box" id="order-summary">
          <div class="box-header">
            <h3>Order summary</h3>
          </div>
          <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <tr>
                  <td>Order subtotal</td>
                  <th>
                    <%= number_to_currency(current_cart.total, unit: "₹ ") %>
                  </th>
                </tr>
                <tr>
                  <td>Shipping and handling</td>
                  <th>0.00</th>
                </tr>
                <tr>
                  <td>Tax</td>
                  <th>0.00</th>
                </tr>
                <tr class="total">
                  <td>Total</td>
                  <th>
                    <%= number_to_currency(current_cart.total, unit: "₹ ") %>
                  </th>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <!-- /.col-md-3 -->
    </div>
    <!-- /.container -->
  </div>
  <!-- /#content -->
</div>
<br>
<br>