config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

class LandingConstraint
  def self.matches?(request)
    domains = %w{ www.lvh.me lvh.me localhost www.localhost }
    case request.subdomain
    when '', 'www'
     domains.include?(request.domain)
    else
      false
    end
  end
end

Rails.application.routes.draw do

  resources :community_product_properties
  resources :community_products

  root to: "home#index"
  get '/product/show', to: "home#show"
  resources :shop_registration

  resources :main_products
  # devise_for :site_admins
  devise_for :site_admins, controllers: {
    sessions: 'site_admins/sessions'
  }
  as :site_admin do
    get '/site_admin_login', to: 'site_admins/sessions#new', as: 'site_admin_login'
    get '/site_admin_logout', to: 'site_admins/sessions#destroy', as: 'site_admin_logout', via: Devise.mappings[:site_admin].sign_out_via
    get '/site_admin_signup', to: 'site_admins/registrations#new', as: 'site_admin_signup'
  end


  devise_for :customers, controllers: {
    sessions: 'customers/sessions'
  }
  as :customer do
    get '/customer_login', to: 'customers/sessions#new', as: 'customer_login'
    get '/customer_logout', to: 'customers/sessions#destroy', as: 'customer_logout', via: Devise.mappings[:customer].sign_out_via
    get '/customer_signup', to: 'customers/registrations#new', as: 'customer_signup'
  end

  # For the ShopknektV2
  constraints LandingConstraint do
    resources :themes
    namespace :control_panel do
      resources :shops

    end
  end

  # For Tenants sites.
  constraints SubdomainConstraint do
    namespace :control_panel do
      resources :product_segments
      resources :categories
      resources :subcategories
      resources :products
      resources :product_properties

      resources :community_products
    end
    # devise_for :customers
    # devise_for :customers, controllers: {
    #   sessions: 'customers/sessions'
    # }
    resources :orders
    resources :order_items
    resources :carts
      resources :shipping_addresses

    resource :cart, only: %i[update show destroy] do
      member do
        put :remove_item
        get :checkout_address
        get :checkout_review
        get :checkout_payment
      end
    end

    resources :customers, only: %i[new create update] do
      # devise_for :users, only: [ :new, :create, :update ]
      # as :user do
      resources :orders
    end

  end

end

app/models/community_product_property.rb
class CommunityProductProperty < ApplicationRecord
  belongs_to :community_product
end

app/controllers/community_product_properties_controller.rb
class CommunityProductPropertiesController < ApplicationController
  before_action :set_community_product_property, only: [:show, :edit, :update, :destroy]

  # GET /community_product_properties
  # GET /community_product_properties.json
  def index
    @community_product_properties = CommunityProductProperty.all
  end

  # GET /community_product_properties/1
  # GET /community_product_properties/1.json
  def show
  end

  # GET /community_product_properties/new
  def new
    @community_product_property = CommunityProductProperty.new
  end

  # GET /community_product_properties/1/edit
  def edit
  end

  # POST /community_product_properties
  # POST /community_product_properties.json
  def create
    @community_product_property = CommunityProductProperty.new(community_product_property_params)

    respond_to do |format|
      if @community_product_property.save
        format.html { redirect_to @community_product_property, notice: 'Community product property was successfully created.' }
        format.json { render :show, status: :created, location: @community_product_property }
      else
        format.html { render :new }
        format.json { render json: @community_product_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /community_product_properties/1
  # PATCH/PUT /community_product_properties/1.json
  def update
    respond_to do |format|
      if @community_product_property.update(community_product_property_params)
        format.html { redirect_to @community_product_property, notice: 'Community product property was successfully updated.' }
        format.json { render :show, status: :ok, location: @community_product_property }
      else
        format.html { render :edit }
        format.json { render json: @community_product_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /community_product_properties/1
  # DELETE /community_product_properties/1.json
  def destroy
    @community_product_property.destroy
    respond_to do |format|
      format.html { redirect_to community_product_properties_url, notice: 'Community product property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community_product_property
      @community_product_property = CommunityProductProperty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_product_property_params
      params.require(:community_product_property).permit(:community_product_id, :size, :color, :quantity)
    end
end

app/helpers/community_product_properties_helper.rb
module CommunityProductPropertiesHelper
end

app/views/community_product_properties/_form.html.erb
<%= form_with(model: community_product_property, local: true) do |form| %>
  <% if community_product_property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community_product_property.errors.count, "error") %> prohibited this community_product_property from being saved:</h2>

      <ul>
      <% community_product_property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :community_product_id %>
    <%= form.text_field :community_product_id, id: :community_product_property_community_product_id %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size, id: :community_product_property_size %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :community_product_property_color %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :community_product_property_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/community_product_properties/edit.html.erb
<h1>Editing Community Product Property</h1>

<%= render 'form', community_product_property: @community_product_property %>

<%= link_to 'Show', @community_product_property %> |
<%= link_to 'Back', community_product_properties_path %>

app/views/community_product_properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Community Product Properties</h1>

<table>
  <thead>
    <tr>
      <th>Community product</th>
      <th>Size</th>
      <th>Color</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @community_product_properties.each do |community_product_property| %>
      <tr>
        <td><%= community_product_property.community_product %></td>
        <td><%= community_product_property.size %></td>
        <td><%= community_product_property.color %></td>
        <td><%= community_product_property.quantity %></td>
        <td><%= link_to 'Show', community_product_property %></td>
        <td><%= link_to 'Edit', edit_community_product_property_path(community_product_property) %></td>
        <td><%= link_to 'Destroy', community_product_property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Community Product Property', new_community_product_property_path %>

app/views/community_product_properties/new.html.erb
<h1>New Community Product Property</h1>

<%= render 'form', community_product_property: @community_product_property %>

<%= link_to 'Back', community_product_properties_path %>

app/views/community_product_properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Community product:</strong>
  <%= @community_product_property.community_product %>
</p>

<p>
  <strong>Size:</strong>
  <%= @community_product_property.size %>
</p>

<p>
  <strong>Color:</strong>
  <%= @community_product_property.color %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @community_product_property.quantity %>
</p>

<%= link_to 'Edit', edit_community_product_property_path(@community_product_property) %> |
<%= link_to 'Back', community_product_properties_path %>