config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

class LandingConstraint
  def self.matches?(request)
    domains = %w{ www.lvh.me lvh.me localhost www.localhost }
    case request.subdomain
    when '', 'www'
     domains.include?(request.domain)
    else
      false
    end
  end
end

Rails.application.routes.draw do

  resources :community_product_properties
  resources :community_products

  root to: "home#index"
  get '/product/show', to: "home#show"
  resources :shop_registration

  resources :main_products
  # devise_for :site_admins
  devise_for :site_admins, controllers: {
    sessions: 'site_admins/sessions'
  }
  as :site_admin do
    get '/site_admin_login', to: 'site_admins/sessions#new', as: 'site_admin_login'
    get '/site_admin_logout', to: 'site_admins/sessions#destroy', as: 'site_admin_logout', via: Devise.mappings[:site_admin].sign_out_via
    get '/site_admin_signup', to: 'site_admins/registrations#new', as: 'site_admin_signup'
  end


  devise_for :customers, controllers: {
    sessions: 'customers/sessions'
  }
  as :customer do
    get '/customer_login', to: 'customers/sessions#new', as: 'customer_login'
    get '/customer_logout', to: 'customers/sessions#destroy', as: 'customer_logout', via: Devise.mappings[:customer].sign_out_via
    get '/customer_signup', to: 'customers/registrations#new', as: 'customer_signup'
  end

  # For the ShopknektV2
  constraints LandingConstraint do
    resources :themes
    namespace :control_panel do
      resources :shops

    end
  end

  # For Tenants sites.
  constraints SubdomainConstraint do
    namespace :control_panel do
      resources :product_segments
      resources :categories
      resources :subcategories
      resources :products
      resources :product_properties

      resources :community_products
    end
    # devise_for :customers
    # devise_for :customers, controllers: {
    #   sessions: 'customers/sessions'
    # }
    resources :orders
    resources :order_items
    resources :carts
      resources :shipping_addresses

    resource :cart, only: %i[update show destroy] do
      member do
        put :remove_item
        get :checkout_address
        get :checkout_review
        get :checkout_payment
      end
    end

    resources :customers, only: %i[new create update] do
      # devise_for :users, only: [ :new, :create, :update ]
      # as :user do
      resources :orders
    end

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShaktimanV2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div id="navbar">
     <ul>
         <li><%= link_to "Home", '/' %></li>
         <% if current_site_admin.present? %>
           <li><%= link_to "Shops", control_panel_shops_path, class: "btn-ghost" %></li>
           <li><%= button_to "Sign Out", destroy_site_admin_session_path, method: :delete, :id => "button" %></li>
         <% else %>
           <li><%= link_to "Sign In", new_site_admin_session_path, class: "btn-ghost" %></li>
           <li><%= link_to "Register Now", new_registration_path, class: "btn-ghost" %></li>
         <% end %>
     </ul>
   </div>

   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

   <div class="content">
     <h1>Shopknekt v2</h1>
     <%= yield %>
   </div>

   <div class="footer"> Shopknekt-V2 <strong>@2018</strong>.</div>


  </body>
</html>